<?php

namespace AppBundle\Repository;

/**
 * Cart_ItemRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Cart_ItemRepository extends \Doctrine\ORM\EntityRepository
{
}
