<?php

namespace AppBundle\Repository;

/**
 * Customer_OrderRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Customer_OrderRepository extends \Doctrine\ORM\EntityRepository
{
}
