<?php

namespace AppBundle\Repository;

/**
 * Order_ItemRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Order_ItemRepository extends \Doctrine\ORM\EntityRepository
{
}
