<?php

namespace AppBundle\Repository;

/**
 * Password_Reset_TokenRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Password_Reset_TokenRepository extends \Doctrine\ORM\EntityRepository
{
}
